"""baseline schema

Everything app/models.py defined before migrations existed. Nothing here is
hand-written — it was generated with `alembic revision --autogenerate`
against an empty database and checked to match `Base.metadata` exactly, so
this is the schema every existing deployment is already running.

Revision ID: 967bc7ac782d
Revises:
Create Date: 2026-09-12 21:42:43.210511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '967bc7ac782d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_name'), 'clusters', ['name'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_table('metric_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_scope_ts', 'metric_samples', ['scope', 'scope_id', 'ts'], unique=False)
    op.create_table('model_specs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('hf_repo', sa.String(length=255), nullable=False),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('params_b', sa.Float(), nullable=False),
    sa.Column('quantization', sa.String(length=32), nullable=False),
    sa.Column('min_gpu_memory_gb', sa.Float(), nullable=False),
    sa.Column('recommended_tp', sa.Integer(), nullable=False),
    sa.Column('max_model_len', sa.Integer(), nullable=False),
    sa.Column('extra_args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vllm_image', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_specs_key'), 'model_specs', ['key'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('max_gpus', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_user', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('dgx', 'workstation', name='nodekind'), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'online', 'unreachable', 'draining', 'maintenance', name='nodestatus'), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('driver_version', sa.String(length=32), nullable=False),
    sa.Column('cuda_version', sa.String(length=32), nullable=False),
    sa.Column('docker_version', sa.String(length=64), nullable=False),
    sa.Column('cpu_count', sa.Integer(), nullable=False),
    sa.Column('memory_gb', sa.Float(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_cluster_id'), 'nodes', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'deployer', 'viewer', name='role'), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('served_model_name', sa.String(length=128), nullable=False),
    sa.Column('spec_id', sa.String(length=36), nullable=True),
    sa.Column('hf_repo', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('gpu_indices', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'pulling', 'starting', 'healthy', 'degraded', 'failed', 'stopping', 'stopped', name='deploystatus'), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=False),
    sa.Column('container_name', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('vllm_args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tensor_parallel_size', sa.Integer(), nullable=False),
    sa.Column('litellm_model_id', sa.String(length=64), nullable=False),
    sa.Column('litellm_registered', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('last_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('healthy_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spec_id'], ['model_specs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_created_at'), 'deployments', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployments_node_id'), 'deployments', ['node_id'], unique=False)
    op.create_index(op.f('ix_deployments_served_model_name'), 'deployments', ['served_model_name'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_table('gpus',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('memory_total_mb', sa.Integer(), nullable=False),
    sa.Column('memory_used_mb', sa.Integer(), nullable=False),
    sa.Column('utilization', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('power_draw_w', sa.Float(), nullable=False),
    sa.Column('power_limit_w', sa.Float(), nullable=False),
    sa.Column('ecc_errors', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'index', name='uq_gpu_node_index')
    )
    op.create_index(op.f('ix_gpus_node_id'), 'gpus', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpus_node_id'), table_name='gpus')
    op.drop_table('gpus')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_served_model_name'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_node_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_created_at'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_cluster_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_table('teams')
    op.drop_index(op.f('ix_model_specs_key'), table_name='model_specs')
    op.drop_table('model_specs')
    op.drop_index('ix_metric_scope_ts', table_name='metric_samples')
    op.drop_table('metric_samples')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_clusters_name'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

    # Postgres ENUM columns create a standalone named type that DROP TABLE
    # does not touch — left alone, the next upgrade's CREATE TYPE collides
    # with it. SQLite has no such type, so this is a no-op there.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in ("deploystatus", "role", "nodestatus", "nodekind"):
            postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
